# Name your project
name: 'product_analytics'
version: '1.0.0'
config-version: 2

dbt-cloud:
    project-id: 70471823466746 #70471823466746
    
# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  +persist_docs:
      relation: true
      columns: true
      
  product_analytics:
    utilities:
      +materialized: view
      +schema: utilities
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: table
      +schema: intermediate
    marts:
      +materialized: table
      +schema: marts

snapshots:
  +persist_docs:
      relation: true
      columns: true

  product_analytics:
      +materialized: snapshot
      +schema: snapshots
