# Name your project
name: 'product_analytics'
version: '1.0.0'
config-version: 2

dbt-cloud:
    project-id: 70471823466746 #70471823466746
    
# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  +persist_docs:
      relation: true
      columns: true

  elementary:
    +schema: "elementary"
    ## To disable elementary for dev, uncomment this:
    # enabled: "{{ target.name in ['prod','analytics'] }}"

  product_analytics:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: intermediate
    warehouse:
      +materialized: table
      +schema: warehouse
    marts:
      +materialized: table
      +schema: marts

snapshots:
  product_analytics:
    +schema: snapshots
  
  +persist_docs:
      relation: true
      columns: true

seeds:
  product_analytics:
    +schema: seeds


flags:
  require_explicit_package_overrides_for_builtin_materializations: false
  source_freshness_run_project_hooks: true
  warn_error_options:
    silence:
      - PackageMaterializationOverrideDeprecation

vars:
  # School year configuration
  school_year_start_month: 7    # July 1st
  school_year_start_day: 1
  school_year_end_month: 6      # June 30th
  school_year_end_day: 30

  # dbt_valid_to_current: "cast('9999-12-31' as timestamp)"