-- Generated by scripts/generate_saved_queries.py
-- Purpose: Union all export tables with standardized time grain dimensions for BI parameterization

with

  qexptbl_day_all as (
    select
      event__metric_time_day__day as date_at_time_grain,
      'day' as time_grain,
      'all' as dim_set,

      'All' as dim_a_label,
      'All' as dim_a_value,
      null as dim_b_label,
      cast(null as varchar) as dim_b_value,

      n_active_users
      , n_events

    from {{ source('exports', 'qexptbl_day_all') }}
  ),

  qexptbl_day_program_name as (
    select
      event__metric_time_day__day as date_at_time_grain,
      'day' as time_grain,
      'program_name' as dim_set,

      'program__program_name' as dim_a_label,
      program__program_name as dim_a_value,
      null as dim_b_label,
      cast(null as varchar) as dim_b_value,

      n_active_users
      , n_events

    from {{ source('exports', 'qexptbl_day_program_name') }}
  ),

  qexptbl_day_resource_type as (
    select
      event__metric_time_day__day as date_at_time_grain,
      'day' as time_grain,
      'resource_type' as dim_set,

      'resource__resource_type' as dim_a_label,
      resource__resource_type as dim_a_value,
      null as dim_b_label,
      cast(null as varchar) as dim_b_value,

      n_active_users
      , n_events

    from {{ source('exports', 'qexptbl_day_resource_type') }}
  ),

  qexptbl_day_district_name as (
    select
      event__metric_time_day__day as date_at_time_grain,
      'day' as time_grain,
      'district_name' as dim_set,

      'district__district_name' as dim_a_label,
      district__district_name as dim_a_value,
      null as dim_b_label,
      cast(null as varchar) as dim_b_value,

      n_active_users
      , n_events

    from {{ source('exports', 'qexptbl_day_district_name') }}
  ),

  qexptbl_day_district_type as (
    select
      event__metric_time_day__day as date_at_time_grain,
      'day' as time_grain,
      'district_type' as dim_set,

      'district__district_type' as dim_a_label,
      district__district_type as dim_a_value,
      null as dim_b_label,
      cast(null as varchar) as dim_b_value,

      n_active_users
      , n_events

    from {{ source('exports', 'qexptbl_day_district_type') }}
  ),

  qexptbl_day_application_name as (
    select
      event__metric_time_day__day as date_at_time_grain,
      'day' as time_grain,
      'application_name' as dim_set,

      'event__application_name' as dim_a_label,
      event__application_name as dim_a_value,
      null as dim_b_label,
      cast(null as varchar) as dim_b_value,

      n_active_users
      , n_events

    from {{ source('exports', 'qexptbl_day_application_name') }}
  ),

  qexptbl_day_program_name_resource_type as (
    select
      event__metric_time_day__day as date_at_time_grain,
      'day' as time_grain,
      'program_name_resource_type' as dim_set,

      'program__program_name' as dim_a_label,
      program__program_name as dim_a_value,
      'resource__resource_type' as dim_b_label,
      resource__resource_type as dim_b_value,

      n_active_users
      , n_events

    from {{ source('exports', 'qexptbl_day_program_name_resource_type') }}
  ),

  qexptbl_day_program_name_district_name as (
    select
      event__metric_time_day__day as date_at_time_grain,
      'day' as time_grain,
      'program_name_district_name' as dim_set,

      'program__program_name' as dim_a_label,
      program__program_name as dim_a_value,
      'district__district_name' as dim_b_label,
      district__district_name as dim_b_value,

      n_active_users
      , n_events

    from {{ source('exports', 'qexptbl_day_program_name_district_name') }}
  ),

  qexptbl_day_program_name_district_type as (
    select
      event__metric_time_day__day as date_at_time_grain,
      'day' as time_grain,
      'program_name_district_type' as dim_set,

      'program__program_name' as dim_a_label,
      program__program_name as dim_a_value,
      'district__district_type' as dim_b_label,
      district__district_type as dim_b_value,

      n_active_users
      , n_events

    from {{ source('exports', 'qexptbl_day_program_name_district_type') }}
  ),

  qexptbl_day_program_name_application_name as (
    select
      event__metric_time_day__day as date_at_time_grain,
      'day' as time_grain,
      'program_name_application_name' as dim_set,

      'program__program_name' as dim_a_label,
      program__program_name as dim_a_value,
      'event__application_name' as dim_b_label,
      event__application_name as dim_b_value,

      n_active_users
      , n_events

    from {{ source('exports', 'qexptbl_day_program_name_application_name') }}
  ),

  qexptbl_day_resource_type_district_name as (
    select
      event__metric_time_day__day as date_at_time_grain,
      'day' as time_grain,
      'resource_type_district_name' as dim_set,

      'resource__resource_type' as dim_a_label,
      resource__resource_type as dim_a_value,
      'district__district_name' as dim_b_label,
      district__district_name as dim_b_value,

      n_active_users
      , n_events

    from {{ source('exports', 'qexptbl_day_resource_type_district_name') }}
  ),

  qexptbl_day_resource_type_district_type as (
    select
      event__metric_time_day__day as date_at_time_grain,
      'day' as time_grain,
      'resource_type_district_type' as dim_set,

      'resource__resource_type' as dim_a_label,
      resource__resource_type as dim_a_value,
      'district__district_type' as dim_b_label,
      district__district_type as dim_b_value,

      n_active_users
      , n_events

    from {{ source('exports', 'qexptbl_day_resource_type_district_type') }}
  ),

  qexptbl_day_resource_type_application_name as (
    select
      event__metric_time_day__day as date_at_time_grain,
      'day' as time_grain,
      'resource_type_application_name' as dim_set,

      'resource__resource_type' as dim_a_label,
      resource__resource_type as dim_a_value,
      'event__application_name' as dim_b_label,
      event__application_name as dim_b_value,

      n_active_users
      , n_events

    from {{ source('exports', 'qexptbl_day_resource_type_application_name') }}
  ),

  qexptbl_day_district_name_district_type as (
    select
      event__metric_time_day__day as date_at_time_grain,
      'day' as time_grain,
      'district_name_district_type' as dim_set,

      'district__district_name' as dim_a_label,
      district__district_name as dim_a_value,
      'district__district_type' as dim_b_label,
      district__district_type as dim_b_value,

      n_active_users
      , n_events

    from {{ source('exports', 'qexptbl_day_district_name_district_type') }}
  ),

  qexptbl_day_district_name_application_name as (
    select
      event__metric_time_day__day as date_at_time_grain,
      'day' as time_grain,
      'district_name_application_name' as dim_set,

      'district__district_name' as dim_a_label,
      district__district_name as dim_a_value,
      'event__application_name' as dim_b_label,
      event__application_name as dim_b_value,

      n_active_users
      , n_events

    from {{ source('exports', 'qexptbl_day_district_name_application_name') }}
  ),

  qexptbl_day_district_type_application_name as (
    select
      event__metric_time_day__day as date_at_time_grain,
      'day' as time_grain,
      'district_type_application_name' as dim_set,

      'district__district_type' as dim_a_label,
      district__district_type as dim_a_value,
      'event__application_name' as dim_b_label,
      event__application_name as dim_b_value,

      n_active_users
      , n_events

    from {{ source('exports', 'qexptbl_day_district_type_application_name') }}
  ),

  qexptbl_week_all as (
    select
      event__metric_time_week__week as date_at_time_grain,
      'week' as time_grain,
      'all' as dim_set,

      'All' as dim_a_label,
      'All' as dim_a_value,
      null as dim_b_label,
      cast(null as varchar) as dim_b_value,

      n_active_users
      , n_events

    from {{ source('exports', 'qexptbl_week_all') }}
  ),

  qexptbl_week_program_name as (
    select
      event__metric_time_week__week as date_at_time_grain,
      'week' as time_grain,
      'program_name' as dim_set,

      'program__program_name' as dim_a_label,
      program__program_name as dim_a_value,
      null as dim_b_label,
      cast(null as varchar) as dim_b_value,

      n_active_users
      , n_events

    from {{ source('exports', 'qexptbl_week_program_name') }}
  ),

  qexptbl_week_resource_type as (
    select
      event__metric_time_week__week as date_at_time_grain,
      'week' as time_grain,
      'resource_type' as dim_set,

      'resource__resource_type' as dim_a_label,
      resource__resource_type as dim_a_value,
      null as dim_b_label,
      cast(null as varchar) as dim_b_value,

      n_active_users
      , n_events

    from {{ source('exports', 'qexptbl_week_resource_type') }}
  ),

  qexptbl_week_district_name as (
    select
      event__metric_time_week__week as date_at_time_grain,
      'week' as time_grain,
      'district_name' as dim_set,

      'district__district_name' as dim_a_label,
      district__district_name as dim_a_value,
      null as dim_b_label,
      cast(null as varchar) as dim_b_value,

      n_active_users
      , n_events

    from {{ source('exports', 'qexptbl_week_district_name') }}
  ),

  qexptbl_week_district_type as (
    select
      event__metric_time_week__week as date_at_time_grain,
      'week' as time_grain,
      'district_type' as dim_set,

      'district__district_type' as dim_a_label,
      district__district_type as dim_a_value,
      null as dim_b_label,
      cast(null as varchar) as dim_b_value,

      n_active_users
      , n_events

    from {{ source('exports', 'qexptbl_week_district_type') }}
  ),

  qexptbl_week_application_name as (
    select
      event__metric_time_week__week as date_at_time_grain,
      'week' as time_grain,
      'application_name' as dim_set,

      'event__application_name' as dim_a_label,
      event__application_name as dim_a_value,
      null as dim_b_label,
      cast(null as varchar) as dim_b_value,

      n_active_users
      , n_events

    from {{ source('exports', 'qexptbl_week_application_name') }}
  ),

  qexptbl_week_program_name_resource_type as (
    select
      event__metric_time_week__week as date_at_time_grain,
      'week' as time_grain,
      'program_name_resource_type' as dim_set,

      'program__program_name' as dim_a_label,
      program__program_name as dim_a_value,
      'resource__resource_type' as dim_b_label,
      resource__resource_type as dim_b_value,

      n_active_users
      , n_events

    from {{ source('exports', 'qexptbl_week_program_name_resource_type') }}
  ),

  qexptbl_week_program_name_district_name as (
    select
      event__metric_time_week__week as date_at_time_grain,
      'week' as time_grain,
      'program_name_district_name' as dim_set,

      'program__program_name' as dim_a_label,
      program__program_name as dim_a_value,
      'district__district_name' as dim_b_label,
      district__district_name as dim_b_value,

      n_active_users
      , n_events

    from {{ source('exports', 'qexptbl_week_program_name_district_name') }}
  ),

  qexptbl_week_program_name_district_type as (
    select
      event__metric_time_week__week as date_at_time_grain,
      'week' as time_grain,
      'program_name_district_type' as dim_set,

      'program__program_name' as dim_a_label,
      program__program_name as dim_a_value,
      'district__district_type' as dim_b_label,
      district__district_type as dim_b_value,

      n_active_users
      , n_events

    from {{ source('exports', 'qexptbl_week_program_name_district_type') }}
  ),

  qexptbl_week_program_name_application_name as (
    select
      event__metric_time_week__week as date_at_time_grain,
      'week' as time_grain,
      'program_name_application_name' as dim_set,

      'program__program_name' as dim_a_label,
      program__program_name as dim_a_value,
      'event__application_name' as dim_b_label,
      event__application_name as dim_b_value,

      n_active_users
      , n_events

    from {{ source('exports', 'qexptbl_week_program_name_application_name') }}
  ),

  qexptbl_week_resource_type_district_name as (
    select
      event__metric_time_week__week as date_at_time_grain,
      'week' as time_grain,
      'resource_type_district_name' as dim_set,

      'resource__resource_type' as dim_a_label,
      resource__resource_type as dim_a_value,
      'district__district_name' as dim_b_label,
      district__district_name as dim_b_value,

      n_active_users
      , n_events

    from {{ source('exports', 'qexptbl_week_resource_type_district_name') }}
  ),

  qexptbl_week_resource_type_district_type as (
    select
      event__metric_time_week__week as date_at_time_grain,
      'week' as time_grain,
      'resource_type_district_type' as dim_set,

      'resource__resource_type' as dim_a_label,
      resource__resource_type as dim_a_value,
      'district__district_type' as dim_b_label,
      district__district_type as dim_b_value,

      n_active_users
      , n_events

    from {{ source('exports', 'qexptbl_week_resource_type_district_type') }}
  ),

  qexptbl_week_resource_type_application_name as (
    select
      event__metric_time_week__week as date_at_time_grain,
      'week' as time_grain,
      'resource_type_application_name' as dim_set,

      'resource__resource_type' as dim_a_label,
      resource__resource_type as dim_a_value,
      'event__application_name' as dim_b_label,
      event__application_name as dim_b_value,

      n_active_users
      , n_events

    from {{ source('exports', 'qexptbl_week_resource_type_application_name') }}
  ),

  qexptbl_week_district_name_district_type as (
    select
      event__metric_time_week__week as date_at_time_grain,
      'week' as time_grain,
      'district_name_district_type' as dim_set,

      'district__district_name' as dim_a_label,
      district__district_name as dim_a_value,
      'district__district_type' as dim_b_label,
      district__district_type as dim_b_value,

      n_active_users
      , n_events

    from {{ source('exports', 'qexptbl_week_district_name_district_type') }}
  ),

  qexptbl_week_district_name_application_name as (
    select
      event__metric_time_week__week as date_at_time_grain,
      'week' as time_grain,
      'district_name_application_name' as dim_set,

      'district__district_name' as dim_a_label,
      district__district_name as dim_a_value,
      'event__application_name' as dim_b_label,
      event__application_name as dim_b_value,

      n_active_users
      , n_events

    from {{ source('exports', 'qexptbl_week_district_name_application_name') }}
  ),

  qexptbl_week_district_type_application_name as (
    select
      event__metric_time_week__week as date_at_time_grain,
      'week' as time_grain,
      'district_type_application_name' as dim_set,

      'district__district_type' as dim_a_label,
      district__district_type as dim_a_value,
      'event__application_name' as dim_b_label,
      event__application_name as dim_b_value,

      n_active_users
      , n_events

    from {{ source('exports', 'qexptbl_week_district_type_application_name') }}
  ),

  qexptbl_month_all as (
    select
      event__metric_time_month__month as date_at_time_grain,
      'month' as time_grain,
      'all' as dim_set,

      'All' as dim_a_label,
      'All' as dim_a_value,
      null as dim_b_label,
      cast(null as varchar) as dim_b_value,

      n_active_users
      , n_events

    from {{ source('exports', 'qexptbl_month_all') }}
  ),

  qexptbl_month_program_name as (
    select
      event__metric_time_month__month as date_at_time_grain,
      'month' as time_grain,
      'program_name' as dim_set,

      'program__program_name' as dim_a_label,
      program__program_name as dim_a_value,
      null as dim_b_label,
      cast(null as varchar) as dim_b_value,

      n_active_users
      , n_events

    from {{ source('exports', 'qexptbl_month_program_name') }}
  ),

  qexptbl_month_resource_type as (
    select
      event__metric_time_month__month as date_at_time_grain,
      'month' as time_grain,
      'resource_type' as dim_set,

      'resource__resource_type' as dim_a_label,
      resource__resource_type as dim_a_value,
      null as dim_b_label,
      cast(null as varchar) as dim_b_value,

      n_active_users
      , n_events

    from {{ source('exports', 'qexptbl_month_resource_type') }}
  ),

  qexptbl_month_district_name as (
    select
      event__metric_time_month__month as date_at_time_grain,
      'month' as time_grain,
      'district_name' as dim_set,

      'district__district_name' as dim_a_label,
      district__district_name as dim_a_value,
      null as dim_b_label,
      cast(null as varchar) as dim_b_value,

      n_active_users
      , n_events

    from {{ source('exports', 'qexptbl_month_district_name') }}
  ),

  qexptbl_month_district_type as (
    select
      event__metric_time_month__month as date_at_time_grain,
      'month' as time_grain,
      'district_type' as dim_set,

      'district__district_type' as dim_a_label,
      district__district_type as dim_a_value,
      null as dim_b_label,
      cast(null as varchar) as dim_b_value,

      n_active_users
      , n_events

    from {{ source('exports', 'qexptbl_month_district_type') }}
  ),

  qexptbl_month_application_name as (
    select
      event__metric_time_month__month as date_at_time_grain,
      'month' as time_grain,
      'application_name' as dim_set,

      'event__application_name' as dim_a_label,
      event__application_name as dim_a_value,
      null as dim_b_label,
      cast(null as varchar) as dim_b_value,

      n_active_users
      , n_events

    from {{ source('exports', 'qexptbl_month_application_name') }}
  ),

  qexptbl_month_program_name_resource_type as (
    select
      event__metric_time_month__month as date_at_time_grain,
      'month' as time_grain,
      'program_name_resource_type' as dim_set,

      'program__program_name' as dim_a_label,
      program__program_name as dim_a_value,
      'resource__resource_type' as dim_b_label,
      resource__resource_type as dim_b_value,

      n_active_users
      , n_events

    from {{ source('exports', 'qexptbl_month_program_name_resource_type') }}
  ),

  qexptbl_month_program_name_district_name as (
    select
      event__metric_time_month__month as date_at_time_grain,
      'month' as time_grain,
      'program_name_district_name' as dim_set,

      'program__program_name' as dim_a_label,
      program__program_name as dim_a_value,
      'district__district_name' as dim_b_label,
      district__district_name as dim_b_value,

      n_active_users
      , n_events

    from {{ source('exports', 'qexptbl_month_program_name_district_name') }}
  ),

  qexptbl_month_program_name_district_type as (
    select
      event__metric_time_month__month as date_at_time_grain,
      'month' as time_grain,
      'program_name_district_type' as dim_set,

      'program__program_name' as dim_a_label,
      program__program_name as dim_a_value,
      'district__district_type' as dim_b_label,
      district__district_type as dim_b_value,

      n_active_users
      , n_events

    from {{ source('exports', 'qexptbl_month_program_name_district_type') }}
  ),

  qexptbl_month_program_name_application_name as (
    select
      event__metric_time_month__month as date_at_time_grain,
      'month' as time_grain,
      'program_name_application_name' as dim_set,

      'program__program_name' as dim_a_label,
      program__program_name as dim_a_value,
      'event__application_name' as dim_b_label,
      event__application_name as dim_b_value,

      n_active_users
      , n_events

    from {{ source('exports', 'qexptbl_month_program_name_application_name') }}
  ),

  qexptbl_month_resource_type_district_name as (
    select
      event__metric_time_month__month as date_at_time_grain,
      'month' as time_grain,
      'resource_type_district_name' as dim_set,

      'resource__resource_type' as dim_a_label,
      resource__resource_type as dim_a_value,
      'district__district_name' as dim_b_label,
      district__district_name as dim_b_value,

      n_active_users
      , n_events

    from {{ source('exports', 'qexptbl_month_resource_type_district_name') }}
  ),

  qexptbl_month_resource_type_district_type as (
    select
      event__metric_time_month__month as date_at_time_grain,
      'month' as time_grain,
      'resource_type_district_type' as dim_set,

      'resource__resource_type' as dim_a_label,
      resource__resource_type as dim_a_value,
      'district__district_type' as dim_b_label,
      district__district_type as dim_b_value,

      n_active_users
      , n_events

    from {{ source('exports', 'qexptbl_month_resource_type_district_type') }}
  ),

  qexptbl_month_resource_type_application_name as (
    select
      event__metric_time_month__month as date_at_time_grain,
      'month' as time_grain,
      'resource_type_application_name' as dim_set,

      'resource__resource_type' as dim_a_label,
      resource__resource_type as dim_a_value,
      'event__application_name' as dim_b_label,
      event__application_name as dim_b_value,

      n_active_users
      , n_events

    from {{ source('exports', 'qexptbl_month_resource_type_application_name') }}
  ),

  qexptbl_month_district_name_district_type as (
    select
      event__metric_time_month__month as date_at_time_grain,
      'month' as time_grain,
      'district_name_district_type' as dim_set,

      'district__district_name' as dim_a_label,
      district__district_name as dim_a_value,
      'district__district_type' as dim_b_label,
      district__district_type as dim_b_value,

      n_active_users
      , n_events

    from {{ source('exports', 'qexptbl_month_district_name_district_type') }}
  ),

  qexptbl_month_district_name_application_name as (
    select
      event__metric_time_month__month as date_at_time_grain,
      'month' as time_grain,
      'district_name_application_name' as dim_set,

      'district__district_name' as dim_a_label,
      district__district_name as dim_a_value,
      'event__application_name' as dim_b_label,
      event__application_name as dim_b_value,

      n_active_users
      , n_events

    from {{ source('exports', 'qexptbl_month_district_name_application_name') }}
  ),

  qexptbl_month_district_type_application_name as (
    select
      event__metric_time_month__month as date_at_time_grain,
      'month' as time_grain,
      'district_type_application_name' as dim_set,

      'district__district_type' as dim_a_label,
      district__district_type as dim_a_value,
      'event__application_name' as dim_b_label,
      event__application_name as dim_b_value,

      n_active_users
      , n_events

    from {{ source('exports', 'qexptbl_month_district_type_application_name') }}
  )


-- Union all tables
  select * from qexptbl_day_all
  union all
  select * from qexptbl_day_program_name
  union all
  select * from qexptbl_day_resource_type
  union all
  select * from qexptbl_day_district_name
  union all
  select * from qexptbl_day_district_type
  union all
  select * from qexptbl_day_application_name
  union all
  select * from qexptbl_day_program_name_resource_type
  union all
  select * from qexptbl_day_program_name_district_name
  union all
  select * from qexptbl_day_program_name_district_type
  union all
  select * from qexptbl_day_program_name_application_name
  union all
  select * from qexptbl_day_resource_type_district_name
  union all
  select * from qexptbl_day_resource_type_district_type
  union all
  select * from qexptbl_day_resource_type_application_name
  union all
  select * from qexptbl_day_district_name_district_type
  union all
  select * from qexptbl_day_district_name_application_name
  union all
  select * from qexptbl_day_district_type_application_name
  union all
  select * from qexptbl_week_all
  union all
  select * from qexptbl_week_program_name
  union all
  select * from qexptbl_week_resource_type
  union all
  select * from qexptbl_week_district_name
  union all
  select * from qexptbl_week_district_type
  union all
  select * from qexptbl_week_application_name
  union all
  select * from qexptbl_week_program_name_resource_type
  union all
  select * from qexptbl_week_program_name_district_name
  union all
  select * from qexptbl_week_program_name_district_type
  union all
  select * from qexptbl_week_program_name_application_name
  union all
  select * from qexptbl_week_resource_type_district_name
  union all
  select * from qexptbl_week_resource_type_district_type
  union all
  select * from qexptbl_week_resource_type_application_name
  union all
  select * from qexptbl_week_district_name_district_type
  union all
  select * from qexptbl_week_district_name_application_name
  union all
  select * from qexptbl_week_district_type_application_name
  union all
  select * from qexptbl_month_all
  union all
  select * from qexptbl_month_program_name
  union all
  select * from qexptbl_month_resource_type
  union all
  select * from qexptbl_month_district_name
  union all
  select * from qexptbl_month_district_type
  union all
  select * from qexptbl_month_application_name
  union all
  select * from qexptbl_month_program_name_resource_type
  union all
  select * from qexptbl_month_program_name_district_name
  union all
  select * from qexptbl_month_program_name_district_type
  union all
  select * from qexptbl_month_program_name_application_name
  union all
  select * from qexptbl_month_resource_type_district_name
  union all
  select * from qexptbl_month_resource_type_district_type
  union all
  select * from qexptbl_month_resource_type_application_name
  union all
  select * from qexptbl_month_district_name_district_type
  union all
  select * from qexptbl_month_district_name_application_name
  union all
  select * from qexptbl_month_district_type_application_name
;
